const SESSIONSTATUSES = {
   REQUESTED: "REQUESTED",
   CONFIRMED: "CONFIRMED",
   IN_PROGRESS: "IN_PROGRESS",
   PHOTOS_PENDING: "PHOTOS_PENDING",
   COMPLETED: "COMPLETED",
   CANCELLED_BY_CLIENT: "CANCELLED_BY_CLIENT",
   CANCELLED_BY_ADMIN: "CANCELLED_BY_ADMIN",
};

export default SESSIONSTATUSES;
